baseURL = "/"
languageCode = "en-us"
title = "Marc Wiedermann"
theme = "cocoa"
author = ""

[[menu.main]]
name                   = "Publications"
weight                 = -110
identifier             = "publications"
url                    = "/publications/"

[[menu.main]]
name                   = "Teaching"
weight                 = -110
identifier             = "teaching"
url                    = "/teaching/"

[params]
avatar = "img/profile.jpeg" 
author = "Marc Wiedermann"
selfintro = """Hi, I'm Marc. I hold a PhD in physics and currently work as a
postdoc at the Potsdam Institute for Climate Impact Research. I am interested
in complex networks, complex contagion and social tipping."""
github = "//github.com/marcwie"
email = "marcwie@pik-potsdam.de"
extracssfiles = ["/css/override.css"] 
