baseURL = "/"
languageCode = "en-us"
title = "Marc Wiedermann"
theme = "cocoa"
author = ""
publishDir = "docs"

[[menu.main]]
name                   = "Blog"
weight                 = -110
identifier             = "blog"
url                    = "/blog/"


[[menu.main]]
name                   = "Publications"
weight                 = -110
identifier             = "publications"
url                    = "/publications/"

[[menu.main]]
name                   = "Teaching"
weight                 = -110
identifier             = "teaching"
url                    = "/teaching/"

[[menu.main]]
name                   = "Conferences"
weight                 = -110
identifier             = "conferences"
url                    = "/conferences/"

[[menu.main]]
name                   = "Projects"
weight                 = -110
identifier             = "projects"
url                    = "/projects/"

[params]
avatar = "img/profile.jpeg"
author = "Marc Wiedermann"
selfintro = ""
github = "//github.com/marcwie"
email = "marcw@physik.hu-berlin.de"
extracssfiles = ["/css/override.css"]
linkedin = "//linkedin.com/in/marc-wiedermann-995958210"

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    style = "pygments"
