baseURL = "/"
languageCode = "en-us"
title = "Marc Wiedermann"
theme = "cocoa"
author = ""

[[menu.main]]
name                   = "Publications"
weight                 = -110
identifier             = "publications"
url                    = "/publications/"

[[menu.main]]
name                   = "Teaching"
weight                 = -110
identifier             = "teaching"
url                    = "/teaching/"

[[menu.main]]
name                   = "Conferences"
weight                 = -110
identifier             = "conferences"
url                    = "/conferences/"

[params]
avatar = "img/profile.jpeg" 
author = "Marc Wiedermann"
selfintro = ""
github = "//github.com/marcwie"
email = "marcwie@pik-potsdam.de"
extracssfiles = ["/css/override.css"] 
