baseurl             = "https://marcwie.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-us"
layoutdir           = "layouts"
publishdir          = "docs"
theme               = "cocoa"
author              = "Marc Wiedermann"
title               = "Marc Wiedermann"
#pygmentsuseclasses  = true
#disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
#googleAnalytics     = "UA-123-45"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Publications"
weight                 = -110
identifier             = "publications"
url                    = "/publications/"

[[menu.main]]
name                   = "Teaching"
weight                 = -110
identifier             = "teaching"
url                    = "/teaching/"

[[menu.main]]
name                   = "Conferences"
weight                 = -110
identifier             = "conferences"
url                    = "/conferences/"

[[menu.main]]
name                   = "Projects"
weight                 = -110
identifier             = "projects"
url                    = "/projects/"

[params]
avatar = "img/profile.jpeg"
author = "Marc Wiedermann"
selfintro = ""
github = "//github.com/marcwie"
email = "marcw@physik.hu-berlin.de"
extracssfiles = ["/css/override.css"]
linkedin = "//linkedin.com/in/marc-wiedermann-995958210"
twitter = "//twitter.com/m_wiedermann"

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    style = "pygments"
